---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: redis-cluster
  namespace: redis-cluster
spec:
  clusterSize: 3
  kubernetesConfig:
    image: mgw2168/redis:v6.2.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
#    redisSecret:
#      name: redis-secret
#      key: password
    # imagePullSecrets:
    #   - name: regcred
  redisExporter:
    enabled: true
    image: mgw2168/redis-exporter:1.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
# Environment Variables for Redis Exporter
    # env:
    # - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
    #   value: "true"
    # - name: UI_PROPERTIES_FILE_NAME
    #   valueFrom:
    #     configMapKeyRef:
    #       name: game-demo
    #       key: ui_properties_file_name
    # - name: SECRET_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: mysecret
    #       key: username
  redisLeader:
    redisConfig:
      additionalRedisConfig: redis-external-config
  redisFollower:
    redisConfig:
      additionalRedisConfig: redis-external-config
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: csi-high-capacity
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Mi
  # nodeSelector:
  #   kubernetes.io/hostname: minikube
  # securityContext: {}
  # priorityClassName:
  # Affinity:
  # Tolerations: []

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: redis-cluster
  name: redis-external-config
data:
  redis-external.conf: |
    tcp-keepalive 400
    slowlog-max-len 158
    stream-node-max-bytes 2048
    io-threads 8
    io-threads-do-reads yes
    maxmemory 536870912

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis-cluster
type: Opaque
data:
  password: "TWd3MjE2OEAK"

---
apiVersion: v1
kind: Service
metadata:
  name: redis-metrics-service
  namespace: redis-cluster
spec:
  selector:
    redis_setup_type: cluster
  ports:
    - protocol: TCP
      port: 9121
      targetPort: 9121
  type: ClusterIP
